/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'file' : [] | [ExternalBlob],
  'mimeType' : [] | [string],
  'fileName' : [] | [string],
  'sender' : Principal,
  'timestamp' : Time,
}
export type Recurrence = { 'weekday' : null } |
  { 'weekend' : null } |
  { 'none' : null };
export type RegisterResult = { 'invalidInput' : null } |
  { 'anonymousCaller' : null } |
  { 'slotFull' : null } |
  { 'success' : null } |
  { 'alreadyRegistered' : null };
export type Time = bigint;
export interface TimetableEntry {
  'id' : bigint,
  'day' : string,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'recurrence' : Recurrence,
}
export interface TimetableEntryInput {
  'day' : string,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'recurrence' : Recurrence,
}
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'timeZone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTimetableEntry' : ActorMethod<[TimetableEntryInput], TimetableEntry>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTimetableEntry' : ActorMethod<[bigint], undefined>,
  'getAllCallerTimetableEntries' : ActorMethod<[], Array<TimetableEntry>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string], RegisterResult>,
  'resetSystem' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'sendMessage' : ActorMethod<
    [string, [] | [ExternalBlob], [] | [string], [] | [string]],
    undefined
  >,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateTimetableEntry' : ActorMethod<
    [bigint, TimetableEntryInput],
    TimetableEntry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];