/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Recurrence = IDL.Variant({
  'weekday' : IDL.Null,
  'weekend' : IDL.Null,
  'none' : IDL.Null,
});
export const TimetableEntryInput = IDL.Record({
  'day' : IDL.Text,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'recurrence' : Recurrence,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Nat,
  'day' : IDL.Text,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'recurrence' : Recurrence,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'file' : IDL.Opt(ExternalBlob),
  'mimeType' : IDL.Opt(IDL.Text),
  'fileName' : IDL.Opt(IDL.Text),
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'timeZone' : IDL.Text,
});
export const RegisterResult = IDL.Variant({
  'invalidInput' : IDL.Null,
  'anonymousCaller' : IDL.Null,
  'slotFull' : IDL.Null,
  'success' : IDL.Null,
  'alreadyRegistered' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTimetableEntry' : IDL.Func([TimetableEntryInput], [TimetableEntry], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllCallerTimetableEntries' : IDL.Func(
      [],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
  'resetSystem' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateTimetableEntry' : IDL.Func(
      [IDL.Nat, TimetableEntryInput],
      [TimetableEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Recurrence = IDL.Variant({
    'weekday' : IDL.Null,
    'weekend' : IDL.Null,
    'none' : IDL.Null,
  });
  const TimetableEntryInput = IDL.Record({
    'day' : IDL.Text,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'recurrence' : Recurrence,
  });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Nat,
    'day' : IDL.Text,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'recurrence' : Recurrence,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'file' : IDL.Opt(ExternalBlob),
    'mimeType' : IDL.Opt(IDL.Text),
    'fileName' : IDL.Opt(IDL.Text),
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'timeZone' : IDL.Text,
  });
  const RegisterResult = IDL.Variant({
    'invalidInput' : IDL.Null,
    'anonymousCaller' : IDL.Null,
    'slotFull' : IDL.Null,
    'success' : IDL.Null,
    'alreadyRegistered' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTimetableEntry' : IDL.Func([TimetableEntryInput], [TimetableEntry], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTimetableEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllCallerTimetableEntries' : IDL.Func(
        [],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text], [RegisterResult], []),
    'resetSystem' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateTimetableEntry' : IDL.Func(
        [IDL.Nat, TimetableEntryInput],
        [TimetableEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };